CREATE TABLE IF NOT EXISTS Users (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR,
    Login VARCHAR NOT NULL UNIQUE,
    Email VARCHAR NOT NULL UNIQUE,
    Password VARCHAR NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT NOW()
);