CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS UserSessions (
  Id SERIAL PRIMARY KEY,
  UserId INTEGER NOT NULL REFERENCES Users (Id) ON DELETE CASCADE,
  RefreshToken UUID NOT NULL DEFAULT uuid_generate_v4(),
  UserAgent VARCHAR NOT NULL,
  Fingerprint VARCHAR NOT NULL,
  ExpiresAt TIMESTAMP WITH TIME ZONE NOT NULL,
  CreatedAt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);