CREATE TABLE IF NOT EXISTS Users (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR,
    Login VARCHAR NOT NULL UNIQUE,
    Email VARCHAR NOT NULL UNIQUE,
    PasswordHash BYTEA NOT NULL,
    Salt BYTEA NOT NULL,
    CreatedAt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);