CREATE TABLE IF NOT EXISTS UserSessions (
  Id SERIAL PRIMARY KEY,
  UserId INTEGER NOT NULL REFERENCES Users (Id) ON DELETE CASCADE,
  RefreshToken UUID NOT NULL,
  UserAgent VARCHAR NOT NULL,
  Fingerprint VARCHAR NOT NULL,
  ExpiresAt TIMESTAMP WITH TIME ZONE NOT NULL,
  CreatedAt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);