version: '3'

services:
  postgres-service:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - 55432:5432/tcp
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password@1234
      POSTGRES_DB: pg_db