version: '3'

services:
  postgres-service:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - 55432:5432/tcp
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password@1234
      POSTGRES_DB: postgres
  http-service:
    image: kotzakhar/golang_pet:latest
    container_name: http-container
    ports:
      - 8080:80/tcp
    environment:
      POSTGRES_CONNECTION_STRING: "postgresql://admin:password@1234@postgres-service:5432/postgres"
      PASSWORD_PEPPER: "MyH0rse1sAm@zing"
      PRIVATE_KEY: "MyPr!v@tKey"
      DOMAIN: "localhost:8080"
      ACCESS_TOKEN_ROUTE: "/api/auth"